services:
  - type: web
    name: api-feedback
    plan: free                # optionnel, choisissez le plan adapté
    runtime: python           # indispensable pour indiquer le langage
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -m waitress --listen=0.0.0.0:8000 api_feedback.wsgi:application"
    